### ISSUE TITLE
Can GeoTess models handle parallel access?

### ISSUE THREAD

**Issue by rad-lanl** [sandialabs/GeoTessCPP#6]
Can GeoTess model objects support parallel access (i.e. is there support for multi-threaded environments?)

**Comment by rad-lanl** [comment]
Im working on a parallel routine that requires accessing a GeoTess model to retrieve path weights. Currently, it seems each parallel instance needs to load the GeoTess model separately for the parallelization to work.

I'm wondering if GeoTess supports multithreaded access to a single model instance.

Specifically, is it possible to load the model once and access its parameters in parallel?

**Comment by rad-lanl** [comment]
Confirmed GeoTess CPP can handle parallelized access, must avoid serializing the object to make it work.

**Comment by jkmacc-LANL** [comment]
Thanks for leaving breadcrumbs on this!
